version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: apollonia-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: apollonia-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/apollonia
    depends_on:
      - mongo

volumes:
  mongo-data:
